server:
  port: 8091
  
spring:
  application:
    name: GATEWAY-API
    

    
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/api/**,/api/address/**
        
#      - id: CART-SERVICE
#        uri: lb://CART-SERVICE
#        predicates:
#         - Path=/api/cart/**
        
      - id: INVENTORY-SERVICE
        uri: lb://INVENTORY-SERVICE
        predicates:
        - Path=/api/inventory/**
        
      - id: ORDERMICRO-SERVICE
        uri: lb://ORDERMICRO-SERVICE
        predicates:
        - Path=/api/order/**
        
      - id: PRODUCTCATALOGUE-SERVICE
        uri: lb://PRODUCTCATALOGUE-SERVICE
        predicates:
        - Path=/api/products/**
        
      - id: SHOPPING-SERVICE
        uri: lb://SHOPPING-SERVICE
        predicates:
        - Path=/api/shopping/**  
        
      - id: CART-SERVICE
        uri: lb://CART-SERVICE
        predicates:
        - Path= /api/cart/**
          
               
         
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/        