server:
  port: 8090

spring:
  application:
    name: SHOPPING-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/