server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Ordermicroserv
    username: root
    password: Sarvesh143
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MYSQL8Dialect
      
  application:
    name: ORDERMICRO-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka/      